### PR TITLE
fix: considered content as function

### PR DESCRIPTION
**Pull request by ineshbose**
#591 

I'm not sure I had seen this implemented before, so I'm wondering how it was on the docs 😅 

I've written tests for this, and updated the docs.

However, there would still be some work to do (looking at type definitions), so I'd like feedback and guidance!

PS. If I have your attention on this, could I please ask you to review #583 too? 😉

### CODE REVIEW

**Comment by Atinux** [comment]
Actually I think it comes from this line: https://github.com/nuxt-modules/tailwindcss/blob/c32cadba15dc5cf0242c8f1b7870987a494454ac/src/module.ts#L133

That does not leverage https://github.com/unjs/defu#array-function-merger 🤔

**Comment by ineshbose** [comment]
I missed the usage of `defuArrayFn` here:
https://github.com/nuxt-modules/tailwindcss/blob/c32cadba15dc5cf0242c8f1b7870987a494454ac/src/module.ts#L139

Let me investigate with the written tests!

**Comment by ineshbose** [comment]
The issue also affects this too unfortunately:

https://github.com/nuxt-modules/tailwindcss/blob/c32cadba15dc5cf0242c8f1b7870987a494454ac/src/module.ts#L136

because a function is not an iterable. In this case `typeof tailwindConfig.content === 'function'` may be necessary. All in all, these three lines are affected if I'm not wrong:

https://github.com/nuxt-modules/tailwindcss/blob/c32cadba15dc5cf0242c8f1b7870987a494454ac/src/module.ts#L133-L139

**Comment by ineshbose** [comment]
I think that should help. Please let me know any feedback - I am still wondering about the config type definition.

**Pull request merged**
