### PR TITLE
fix: css intellisense not working

### PR DESCRIPTION
**Pull request by nazar1ua**
Workaround for #593

### CODE REVIEW

**Comment by nazar1ua** [comment]
@Atinux there are also bug with `content`, it isn't working, like documented, there are my `.nuxt/tailwind.config.cjs`:

```js
"files": [
  "utils/**/*.ts",
  "content/**/*.md",
  "/home/nazar/development/website/components/**/*.{vue,js,ts}",
  "/home/nazar/development/website/layouts/**/*.vue",
  "/home/nazar/development/website/pages/**/*.vue",
  "/home/nazar/development/website/composables/**/*.{js,ts}",
  "/home/nazar/development/website/plugins/**/*.{js,ts}",
  "/home/nazar/development/website/App.{js,ts,vue}",
  "/home/nazar/development/website/app.{js,ts,vue}",
  "/home/nazar/development/website/Error.{js,ts,vue}",
  "/home/nazar/development/website/error.{js,ts,vue}"
],
```

So, can I fix it in this pr?

**Comment by nazar1ua** [comment]
I want make this (https://github.com/nuxt-modules/tailwindcss/blob/c32cadba15dc5cf0242c8f1b7870987a494454ac/src/module.ts#L136):
```js
tailwindConfig.content = [...(tailwindConfig.content && tailwindConfig.content.map(src => `${nuxt.options.srcDir}/${src}`) || []), ...contentPaths] // TODO: support `extends` directories
```

**Comment by Atinux** [comment]
@nazar1ua you have to make sure content is added before tailwind module.

**Review by Atinux — APPROVED** [review]

**Comment by nazar1ua** [comment]
@Atinux I'm sorry, but I don't understand you

**Comment by Atinux** [comment]
What's your `nuxt.config.ts` ?

**Comment by nazar1ua** [comment]
Classes are generated correctly, but I think, It would be better, it there will only relative or only absolute paths, not mix of them

**Pull request merged**
