### PR TITLE
build: update merger filename and revert `@nuxt/content` upgrade

### PR DESCRIPTION
**Pull request by danielroe**

### CODE REVIEW

**Comment by ineshbose** [comment]
Thanks for raising this PR but that TODO is what I have been wondering about, as the whole PostCSS/config may be in CJS syntax and/or Nuxt 2 projects may be in CJS. The MJS is explicit and helpful no? What shortcomings were there specifying that extension?

**Comment by danielroe** [comment]
The error is not coming from loading the `merger.js` file. Even when I update it to be `.mjs`, the same warnings are logged.

**Comment by danielroe** [comment]
@ineshbose Seems we have a regression somewhere in that deps upgrade (though not, apparently, in the module-builder update)...

**Review by ineshbose — APPROVED** [review]
Thank you ❤️

**Pull request merged**
