### PR TITLE
feat: `editorSupport` option

### PR DESCRIPTION
**Pull request by ineshbose**
This PR expands on providing editor support utilities as part of the module.

TODO:
- [x] type definitions
- [x] implement code
- [x] Redo some docs

### CODE REVIEW

**Comment by autofix-troubleshooter** [comment]
Hi! I'm the <a href="https://autofix.ci">autofix logo<strong>autofix.ci</strong></a> troubleshooter bot.

It looks like you correctly set up a CI job that uses the autofix.ci GitHub Action, but the [**autofix.ci GitHub App**](https://github.com/apps/autofix-ci/) has not been installed for this repository. This means that autofix.ci unfortunately does not have the permissions to fix this pull request. If you are the repository owner, please install the app and then restart the CI workflow! 😃

**Comment by ineshbose** [comment]
@mitjans I've made some modification to your util; please feel free to share your thoughts on this.

**Comment by Yuri4dev** [comment]
hello???

**Comment by ineshbose** [comment]
I'll merge this for now as I'm looking to build upon this for the next release.

**Pull request merged**
